# Generated by Django 6.1 on 2026-08-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
