"""
Django settings for crowdfunding project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
import dj_database_url
import cloudinary
import cloudinary.uploader
import cloudinary.utils
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# تحميل المتغيرات من ملف .env لضمان قراءة مفتاح جوجل (GEMINI_API_KEY) وباقي الإعدادات
load_dotenv(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-037bbu-(9y4wm0!23()(%%60bkj2zarih+y$!+0r9+_yi+2+cz'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'accounts',
    'projects',
    'interactions',
    'donations.apps.DonationsConfig',
    'chatbot',  # تم إضافة تطبيق الشات بوت هنا
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'anymail',  # تم إضافة anymail هنا
    'cloudinary',
    'cloudinary_storage',
]



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'crowdfunding.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'crowdfunding.wsgi.application'


# Database (تمت إزالة الرابط الصريح تماماً لحماية أمان الداتا بيز)
DATABASES = {
    'default': dj_database_url.parse(
        os.environ.get('DATABASE_URL'), 
        conn_max_age=0
    )
}

# السطرين دول بيكبروا نظام التشغيل إنه يعمل اتصال مشفر إجباري مع السيرفر السحابي
DATABASES['default']['OPTIONS'] = {
    'sslmode': 'require',
}




# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = '/static/'

# ده الفولدر اللي چانجو هيجمع فيه كل ملفات الستايل للرفع
STATIC_ROOT = BASE_DIR / 'staticfiles' 



# ده الفولدر اللي إنت حاطط فيه ملفات الستايل والصور بتاعتك وإنت شغال
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]


# ==========================================
# Email Configuration (Brevo API via Anymail)
# ==========================================
EMAIL_BACKEND = 'anymail.backends.sendinblue.EmailBackend'

ANYMAIL = {
    "SENDINBLUE_API_KEY": os.environ.get('BREVO_API_KEY'),
}

# اسم المرسل اللي هيظهر للناس لما يوصلهم الإيميل
DEFAULT_FROM_EMAIL = 'CrowdFund Team <crowdfunding.team.eg@gmail.com>'

# تحديد صلاحية رابط التفعيل بـ 24 ساعة (بالثواني)
PASSWORD_RESET_TIMEOUT = 86400


# ==========================================
# Media Files
# ==========================================
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


LOGIN_REDIRECT_URL = 'home' 
LOGOUT_REDIRECT_URL = 'login'


# إعدادات الـ Cloudinary
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.environ.get('CLOUDINARY_API_KEY'),
    'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET'),
}


# ==========================================
# Paymob Configuration
# ==========================================
PAYMOB_API_KEY = os.environ.get('PAYMOB_API_KEY')
PAYMOB_SECRET_KEY = os.environ.get('PAYMOB_SECRET_KEY')
PAYMOB_MERCHANT_ID = os.environ.get('PAYMOB_MERCHANT_ID')
PAYMOB_INTEGRATION_ID = os.environ.get('PAYMOB_INTEGRATION_ID')


# ==========================================
# Gemini AI Configuration
# ==========================================
GEMINI_API_KEY = os.environ.get('GEMINI_API_KEY')


STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}