# Generated by Django 6.1 on 2026-08-09 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='wallet',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
